### ISSUE TITLE
Py3 compatibility for smali emulator

### ISSUE THREAD

**Issue by drake-mer** [mikusjelly/smaliemu#4]
Hi, I commited stuff to the original project recently, including:

- migration to pytest for test runner
- addition of some op codes
- command line utils

Currently, the smali_emulator is not ready for py3 (integer issues and other stuff).

Do you think it could be worth it to merge your commits into the mainline ?

Thank you.

**Comment by kin9-0rz** [comment]
Sorry. I don't have time to solve the conflict between the two projects. Maybe you can do it.
